apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-config
  namespace: todo-app
data:
  SERVER_URL: "http://127.0.0.1:3000"
  CLOUDANT_URL: "https://e23f4cca-cf1c-46e0-b5f0-6c4274481c6d-bluemix.cloudantnosqldb.appdomain.cloud"
  CLOUDANT_DB_NAME: "todo-db"
